from tests.virt.constants import REQUESTS_CPU_VMI_STR, REQUESTS_INSTANCES_VMI_STR, REQUESTS_MEMORY_VMI_STR

UPGRADE_QUOTA_FOR_ONE_VMI = {
    REQUESTS_INSTANCES_VMI_STR: "1",
    REQUESTS_CPU_VMI_STR: 1,
    REQUESTS_MEMORY_VMI_STR: "1Gi",
}
