import copy

from tests.install_upgrade_operators.constants import WORKLOAD_UPDATE_STRATEGY_KEY_NAME, WORKLOADUPDATEMETHODS
from utilities.constants import LIVE_MIGRATE

DEFAULT_BATCH_EVICTION_INTERVAL = "1m0s"
DEFAULT_BATCH_EVICTION_SIZE = 10
DEFAULT_WORKLOAD_UPDATE_METHODS = [LIVE_MIGRATE]
DEFAULT_WORKLOAD_UPDATE_STRATEGY = {
    "batchEvictionInterval": DEFAULT_BATCH_EVICTION_INTERVAL,
    "batchEvictionSize": DEFAULT_BATCH_EVICTION_SIZE,
    WORKLOADUPDATEMETHODS: DEFAULT_WORKLOAD_UPDATE_METHODS,
}
CUSTOM_BATCH_EVICTION_INTERVAL_INT = "2500000h0m0s"
CUSTOM_BATCH_EVICTION_SIZE_INT = 100
CUSTOM_BATCH_EVICTION_INTERVAL = "5m0s"
CUSTOM_BATCH_EVICTION_SIZE = 20
CUSTOM_WORKLOAD_UPDATE_METHODS = ["Evict"]
CUSTOM_WORKLOAD_UPDATE_STRATEGY = {
    "batchEvictionInterval": CUSTOM_BATCH_EVICTION_INTERVAL,
    "batchEvictionSize": CUSTOM_BATCH_EVICTION_SIZE,
    WORKLOADUPDATEMETHODS: CUSTOM_WORKLOAD_UPDATE_METHODS,
}
MOD_DEFAULT_BATCH_EVICTION_INTERVAL = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_BATCH_EVICTION_SIZE = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_WORKLOAD_UPDATE_METHOD = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_WORKLOAD_UPDATE_METHOD_EMPTY = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_BATCH_EVICTION_INTERVAL_ZERO = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_BATCH_EVICTION_SIZE_ZERO = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_BATCH_EVICTION_SIZE_INT = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_BATCH_EVICTION_INTERVAL_INT = copy.deepcopy(DEFAULT_WORKLOAD_UPDATE_STRATEGY)
MOD_DEFAULT_BATCH_EVICTION_INTERVAL_ZERO["batchEvictionInterval"] = "0s"
MOD_DEFAULT_BATCH_EVICTION_INTERVAL_INT["batchEvictionInterval"] = CUSTOM_BATCH_EVICTION_INTERVAL_INT
MOD_DEFAULT_BATCH_EVICTION_INTERVAL["batchEvictionInterval"] = CUSTOM_BATCH_EVICTION_INTERVAL
MOD_DEFAULT_BATCH_EVICTION_SIZE_ZERO["batchEvictionSize"] = 0
MOD_DEFAULT_BATCH_EVICTION_SIZE_INT["batchEvictionSize"] = CUSTOM_BATCH_EVICTION_SIZE_INT
MOD_DEFAULT_BATCH_EVICTION_SIZE["batchEvictionSize"] = CUSTOM_BATCH_EVICTION_SIZE
MOD_DEFAULT_WORKLOAD_UPDATE_METHOD[WORKLOADUPDATEMETHODS] = CUSTOM_WORKLOAD_UPDATE_METHODS
MOD_DEFAULT_WORKLOAD_UPDATE_METHOD_EMPTY[WORKLOADUPDATEMETHODS] = []
MOD_CUST_DEFAULT_BATCH_EVICTION_INTERVAL = copy.deepcopy(CUSTOM_WORKLOAD_UPDATE_STRATEGY)
MOD_CUST_DEFAULT_BATCH_EVICTION_SIZE = copy.deepcopy(CUSTOM_WORKLOAD_UPDATE_STRATEGY)
MOD_CUST_DEFAULT_WORKLOAD_UPDATE_METHOD = copy.deepcopy(CUSTOM_WORKLOAD_UPDATE_STRATEGY)
MOD_CUST_DEFAULT_BATCH_EVICTION_INTERVAL["batchEvictionInterval"] = DEFAULT_BATCH_EVICTION_INTERVAL
MOD_CUST_DEFAULT_BATCH_EVICTION_SIZE["batchEvictionSize"] = DEFAULT_BATCH_EVICTION_SIZE
MOD_CUST_DEFAULT_WORKLOAD_UPDATE_METHOD[WORKLOADUPDATEMETHODS] = DEFAULT_WORKLOAD_UPDATE_METHODS

CUSTOM_STRATEGY = {WORKLOAD_UPDATE_STRATEGY_KEY_NAME: CUSTOM_WORKLOAD_UPDATE_STRATEGY}
CUSTOM_WORKLOAD_STRATEGY_SPEC = {"spec": CUSTOM_STRATEGY}
