VM_PREFERENCES_LIST = {
    "unique": [
        "alpine",
        "ubuntu",
        "cirros",
        "fedora",
        "fedora.arm64",
        "fedora.s390x",
        "opensuse.leap",
        "opensuse.tumbleweed",
        "sles",
        "debian",
        "oraclelinux",
    ],
    "centos": ["centos.stream9", "centos.stream10", "centos.stream9.desktop", "centos.stream10.desktop"],
    "rhel": [
        "rhel.7",
        "rhel.8",
        "rhel.9",
        "rhel.10",
        "rhel.9.realtime",
        "rhel.9.arm64",
        "rhel.9.s390x",
        "rhel.10.arm64",
        "rhel.10.s390x",
        "rhel.7.desktop",
        "rhel.8.desktop",
        "rhel.9.desktop",
    ],
    "windows": [
        "windows.10",
        "windows.11",
        "windows.2k16",
        "windows.2k19",
        "windows.2k22",
        "windows.2k25",
        "windows.10.virtio",
        "windows.11.virtio",
        "windows.2k16.virtio",
        "windows.2k19.virtio",
        "windows.2k22.virtio",
        "windows.2k25.virtio",
    ],
    "network": ["centos.stream9.dpdk", "rhel.8.dpdk", "rhel.9.dpdk"],
    "generic": ["legacy", "linux.efi", "linux"],
}
