DESCHEDULER_POD_LABEL = "app=descheduler"
DESCHEDULING_INTERVAL_120SEC = 120
RUNNING_PING_PROCESS_NAME_IN_VM = "ping"
CONFIG_MAP_POLICY_YAML_FILE = "policy.yaml"

NODE_SELECTOR_LABEL = {"descheduler": "test"}
