DESCHEDULING_INTERVAL_120SEC = 120
RUNNING_PING_PROCESS_NAME_IN_VM = "ping"

DESCHEDULER_LABEL_KEY = "descheduler-label"
DESCHEDULER_LABEL_VALUE = "test"
DESCHEDULER_TEST_LABEL = {DESCHEDULER_LABEL_KEY: DESCHEDULER_LABEL_VALUE}

DESCHEDULER_DEPLOYMENT_NAME = "descheduler"

DESCHEDULER_SOFT_TAINT_KEY = "nodeutilization.descheduler.openshift.io"
