from ocp_resources.resource import Resource

from utilities.constants import (
    AAQ_OPERATOR,
    BRIDGE_MARKER,
    CDI_APISERVER,
    CDI_DEPLOYMENT,
    CDI_KUBEVIRT_HYPERCONVERGED,
    CDI_OPERATOR,
    CDI_UPLOADPROXY,
    CLUSTER,
    CLUSTER_NETWORK_ADDONS_OPERATOR,
    CNAO_OPERATOR,
    CREATING_VIRTUAL_MACHINE,
    CREATING_VIRTUAL_MACHINE_FROM_VOLUME,
    GRAFANA_DASHBOARD_KUBEVIRT_TOP_CONSUMERS,
    HCO_BEARER_AUTH,
    HCO_OPERATOR,
    HCO_PART_OF_LABEL_VALUE,
    HCO_WEBHOOK,
    HOSTPATH_PROVISIONER_CSI,
    HOSTPATH_PROVISIONER_OPERATOR,
    HPP_POOL,
    HYPERCONVERGED_CLUSTER,
    HYPERCONVERGED_CLUSTER_CLI_DOWNLOAD,
    HYPERCONVERGED_CLUSTER_OPERATOR_METRICS,
    KUBE_CNI_LINUX_BRIDGE_PLUGIN,
    KUBEMACPOOL_CERT_MANAGER,
    KUBEMACPOOL_MAC_CONTROLLER_MANAGER,
    KUBEVIRT_APISERVER_PROXY,
    KUBEVIRT_CLUSTER_CRITICAL,
    KUBEVIRT_CONSOLE_PLUGIN,
    KUBEVIRT_CONSOLE_PLUGIN_SERVICE,
    KUBEVIRT_HYPERCONVERGED_OPERATOR_METRICS,
    KUBEVIRT_HYPERCONVERGED_PROMETHEUS_RULE,
    KUBEVIRT_IPAM_CONTROLLER_MANAGER,
    KUBEVIRT_KUBEVIRT_HYPERCONVERGED,
    KUBEVIRT_PLUGIN,
    KUBEVIRT_UI_CONFIG,
    KUBEVIRT_UI_CONFIG_READER,
    KUBEVIRT_UI_CONFIG_READER_ROLE_BINDING,
    KUBEVIRT_UI_FEATURES,
    KUBEVIRT_USER_SETTINGS,
    MANAGED_BY_LABEL_VALUE_OLM,
    NGINX_CONF,
    RHEL8_GUEST,
    RHEL9_GUEST,
    RHEL10_BETA_GUEST,
    SSP_KUBEVIRT_HYPERCONVERGED,
    SSP_OPERATOR,
    UPLOAD_BOOT_SOURCE,
    VERSION_LABEL_KEY,
    VIRT_API,
    VIRT_CONTROLLER,
    VIRT_EXPORTPROXY,
    VIRT_HANDLER,
    VIRT_OPERATOR,
    VIRT_TEMPLATE_VALIDATOR,
    VIRTCTL_CLIDOWNLOADS_KUBEVIRT_HYPERCONVERGED,
    VIRTIO_WIN,
    WINDOWS_BOOTSOURCE_PIPELINE,
)

VIRITO_WIN_STORAGE = "virtio-win-storage"
# components
TEMPLATING_STR = "templating"
DEPLOYMENT_STR = "deployment"
MONITORING_STR = "monitoring"
SCHEDULE_STR = "schedule"
COMPUTE_STR = "compute"
IMPORT_STR = "import"
STORAGE_STR = "storage"
NETWORK_STR = "network"
# labels keys
MANAGED_BY_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/managed-by"
COMPONENT_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/component"
PART_OF_LABEL_KEY = f"{Resource.ApiGroup.APP_KUBERNETES_IO}/part-of"
ALL_LABEL_KEYS = [
    MANAGED_BY_LABEL_KEY,
    VERSION_LABEL_KEY,
    COMPONENT_LABEL_KEY,
    PART_OF_LABEL_KEY,
]
# Daemonset expected labels
EXPECTED_VIRT_DAEMONSETS_LABELS_DICT_MAP = {
    BRIDGE_MARKER: {
        MANAGED_BY_LABEL_KEY: CNAO_OPERATOR,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBE_CNI_LINUX_BRIDGE_PLUGIN: {
        MANAGED_BY_LABEL_KEY: CNAO_OPERATOR,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HOSTPATH_PROVISIONER_CSI: {
        MANAGED_BY_LABEL_KEY: HOSTPATH_PROVISIONER_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_HANDLER: {
        MANAGED_BY_LABEL_KEY: VIRT_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
}
# Deployment expected labels
EXPECTED_VIRT_DEPLOYMENTS_LABELS_DICT_MAP = {
    CDI_APISERVER: {
        MANAGED_BY_LABEL_KEY: CDI_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HPP_POOL: {
        MANAGED_BY_LABEL_KEY: HOSTPATH_PROVISIONER_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    CDI_DEPLOYMENT: {
        MANAGED_BY_LABEL_KEY: CDI_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    CDI_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    CDI_UPLOADPROXY: {
        MANAGED_BY_LABEL_KEY: CDI_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    CLUSTER_NETWORK_ADDONS_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HCO_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HCO_WEBHOOK: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HOSTPATH_PROVISIONER_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    SSP_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: SCHEDULE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HYPERCONVERGED_CLUSTER_CLI_DOWNLOAD: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_EXPORTPROXY: {
        MANAGED_BY_LABEL_KEY: VIRT_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEMACPOOL_CERT_MANAGER: {
        MANAGED_BY_LABEL_KEY: CNAO_OPERATOR,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEMACPOOL_MAC_CONTROLLER_MANAGER: {
        MANAGED_BY_LABEL_KEY: CNAO_OPERATOR,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEVIRT_CONSOLE_PLUGIN: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_CONSOLE_PLUGIN,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_API: {
        MANAGED_BY_LABEL_KEY: VIRT_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_CONTROLLER: {
        MANAGED_BY_LABEL_KEY: VIRT_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    VIRT_TEMPLATE_VALIDATOR: {
        MANAGED_BY_LABEL_KEY: SSP_OPERATOR,
        COMPONENT_LABEL_KEY: TEMPLATING_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEVIRT_APISERVER_PROXY: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_APISERVER_PROXY,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    AAQ_OPERATOR: {
        MANAGED_BY_LABEL_KEY: MANAGED_BY_LABEL_VALUE_OLM,
        COMPONENT_LABEL_KEY: "quota-management",
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEVIRT_IPAM_CONTROLLER_MANAGER: {
        MANAGED_BY_LABEL_KEY: CNAO_OPERATOR,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
}
# Pods expected labels
EXPECTED_VIRT_PODS_LABELS_DICT_MAP = {
    **EXPECTED_VIRT_DAEMONSETS_LABELS_DICT_MAP,
    **EXPECTED_VIRT_DEPLOYMENTS_LABELS_DICT_MAP,
}
# OCP resources expected labels
EXPECTED_RELATED_OBJECTS_LABELS_DICT_MAP = {
    KUBEVIRT_HYPERCONVERGED_PROMETHEUS_RULE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: MONITORING_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    HYPERCONVERGED_CLUSTER_OPERATOR_METRICS: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: MONITORING_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_HYPERCONVERGED_OPERATOR_METRICS: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: MONITORING_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_CLUSTER_CRITICAL: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_KUBEVIRT_HYPERCONVERGED: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    CDI_KUBEVIRT_HYPERCONVERGED: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    CLUSTER: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: NETWORK_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    SSP_KUBEVIRT_HYPERCONVERGED: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: SCHEDULE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    VIRTCTL_CLIDOWNLOADS_KUBEVIRT_HYPERCONVERGED: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    HYPERCONVERGED_CLUSTER_CLI_DOWNLOAD: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_CONSOLE_PLUGIN_SERVICE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_CONSOLE_PLUGIN,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    CREATING_VIRTUAL_MACHINE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    UPLOAD_BOOT_SOURCE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    GRAFANA_DASHBOARD_KUBEVIRT_TOP_CONSUMERS: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    RHEL8_GUEST: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    RHEL9_GUEST: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    RHEL10_BETA_GUEST: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    VIRTIO_WIN: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: DEPLOYMENT_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    VIRITO_WIN_STORAGE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: STORAGE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_CONSOLE_PLUGIN: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_CONSOLE_PLUGIN,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    NGINX_CONF: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_CONSOLE_PLUGIN,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_PLUGIN: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_CONSOLE_PLUGIN,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    KUBEVIRT_APISERVER_PROXY: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_APISERVER_PROXY,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HYPERCONVERGED_CLUSTER,
    },
    CREATING_VIRTUAL_MACHINE_FROM_VOLUME: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    WINDOWS_BOOTSOURCE_PIPELINE: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: COMPUTE_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEVIRT_USER_SETTINGS: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_UI_CONFIG,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEVIRT_UI_FEATURES: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_UI_CONFIG,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEVIRT_UI_CONFIG_READER: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_CONSOLE_PLUGIN,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    KUBEVIRT_UI_CONFIG_READER_ROLE_BINDING: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: KUBEVIRT_CONSOLE_PLUGIN,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
    HCO_BEARER_AUTH: {
        MANAGED_BY_LABEL_KEY: HCO_OPERATOR,
        COMPONENT_LABEL_KEY: MONITORING_STR,
        VERSION_LABEL_KEY: None,
        PART_OF_LABEL_KEY: HCO_PART_OF_LABEL_VALUE,
    },
}
