TEST_CLASS_CREATION_VALIDATION = "TestVMCreationAndValidation"
TEST_CREATE_VM_TEST_NAME = f"{TEST_CLASS_CREATION_VALIDATION}::test_create_vm"
TEST_START_VM_TEST_NAME = f"{TEST_CLASS_CREATION_VALIDATION}::test_start_vm"

TESTS_CLASS_MIGRATION = "TestVMMigrationAndState"
TESTS_MIGRATE_VM = f"{TESTS_CLASS_MIGRATION}::test_migrate_vm"
