from tests.virt.constants import (
    LIMITS_CPU_STR,
    LIMITS_MEMORY_STR,
    PODS_STR,
    REQUESTS_CPU_STR,
    REQUESTS_CPU_VMI_STR,
    REQUESTS_INSTANCES_VMI_STR,
    REQUESTS_MEMORY_STR,
    REQUESTS_MEMORY_VMI_STR,
)

POD_REQUESTS_CPU = 2
POD_REQUESTS_MEMORY = "2.5Gi"
POD_LIMITS_CPU = POD_REQUESTS_CPU * 2
POD_LIMITS_MEMORY = f"{float(POD_REQUESTS_MEMORY[:-2]) * 2}Gi"

POD_RESOURCES_SPEC = {
    "resources": {
        "requests": {
            "memory": POD_REQUESTS_MEMORY,
            "cpu": POD_REQUESTS_CPU,
        },
        "limits": {
            "memory": POD_LIMITS_MEMORY,
            "cpu": POD_LIMITS_CPU,
        },
    }
}


QUOTA_FOR_POD = {
    PODS_STR: "1",
    LIMITS_CPU_STR: POD_LIMITS_CPU,
    LIMITS_MEMORY_STR: POD_LIMITS_MEMORY,
    REQUESTS_CPU_STR: POD_REQUESTS_CPU,
    REQUESTS_MEMORY_STR: POD_LIMITS_MEMORY,
}


VM_CPU_CORES = 2
VM_MEMORY_GUEST = "2Gi"

QUOTA_FOR_ONE_VMI = {
    REQUESTS_INSTANCES_VMI_STR: "1",
    REQUESTS_CPU_VMI_STR: VM_CPU_CORES,
    REQUESTS_MEMORY_VMI_STR: VM_MEMORY_GUEST,
}

QUOTA_FOR_TWO_VMI = {
    REQUESTS_INSTANCES_VMI_STR: "2",
    REQUESTS_CPU_VMI_STR: VM_CPU_CORES * 2,
    REQUESTS_MEMORY_VMI_STR: f"{int(VM_MEMORY_GUEST[:-2]) * 2}Gi",
}

ARQ_QUOTA_HARD_SPEC = {**QUOTA_FOR_POD, **QUOTA_FOR_ONE_VMI}

ACRQ_QUOTA_HARD_SPEC = {**QUOTA_FOR_POD, **QUOTA_FOR_TWO_VMI}


CPU_MAX_SOCKETS = 4
MEMORY_MAX_GUEST = "4Gi"
