ERROR_MSG_VM_IS_RUNNING = r".*virtualmachinerestore-validator.snapshot.kubevirt.io.*" r"denied the request*"

VIRTUAL_MACHINES_SNAPSHOT_FORBIDDEN = r".*virtualmachinesnapshots.snapshot.kubevirt.io is forbidden: User"
VIRTUAL_MACHINE_RESTORE_FORBIDDEN = r".*virtualmachinerestores.snapshot.kubevirt.io is forbidden: User"
CANNOT_CREATE_RESOURCE = r"cannot create resource"
CANNOT_LIST_RESOURCE = r"cannot list resource"
VIRTUAL_MACHINES_SNAPSHOTS = r"virtualmachinesnapshots.*snapshot.kubevirt.io"
VIRTUAL_MACHINE_RESTORES = r"virtualmachinerestores.*snapshot.kubevirt.io"
IN_NAMESPACE = r"in the namespace"

ERROR_MSG_USER_CANNOT_CREATE_VM_RESTORE = (
    f"{VIRTUAL_MACHINE_RESTORE_FORBIDDEN}.*{CANNOT_CREATE_RESOURCE}.*{VIRTUAL_MACHINE_RESTORES}.*{IN_NAMESPACE}.*"
)
ERROR_MSG_USER_CANNOT_CREATE_VM_SNAPSHOTS = (
    f"{VIRTUAL_MACHINES_SNAPSHOT_FORBIDDEN}.*{CANNOT_CREATE_RESOURCE}.*{VIRTUAL_MACHINES_SNAPSHOTS}.*{IN_NAMESPACE}.*"
)
ERROR_MSG_USER_CANNOT_LIST_VM_SNAPSHOTS = (
    f"{VIRTUAL_MACHINES_SNAPSHOT_FORBIDDEN}.*{CANNOT_LIST_RESOURCE}.*{VIRTUAL_MACHINES_SNAPSHOTS}.*{IN_NAMESPACE}.*"
)
ERROR_MSG_USER_CANNOT_LIST_VM_RESTORE = (
    f"{VIRTUAL_MACHINE_RESTORE_FORBIDDEN}.*{CANNOT_LIST_RESOURCE}.*{VIRTUAL_MACHINE_RESTORES}.*{IN_NAMESPACE}.*"
)

WINDOWS_DIRECTORY_PATH = r"C:\Users\NewFolder"
